### ISSUE TITLE
How and where can I use this 

### ISSUE THREAD

**Issue by techvoltage** [StanfordPL/strata#2]
Kudos for the great work btw

**Comment by stefanheule** [comment]
All of the code is available, and [stefanheule.com/strata/](https://stefanheule.com/strata/) has a section on how to use Strata.  If you just want to use the formulas, it might be best to use [STOKE](http://stoke.stanford.edu/).  What did you have in mind?

**Comment by techvoltage** [comment]
This seems to be a new thing and has not been done before AFAIK. So I'm still thinking where it can be used. Some ideas that come to mind though:

Formal verification of disassemblers
Processor fuzzing 
Optimizing compiled using semantically equivalent code blocks
Code Mutation and (de) obfuscation

**Comment by stefanheule** [comment]
Those all sounds like good ideas that can benefit from formal specifications of ISAs.
