### ISSUE TITLE
Base formula for AF flag does not seem to be correct

### ISSUE THREAD

**Issue by sdasgup3** [StanfordPL/strata#4]
The ran the following command in the [artifact repository](https://github.com/StanfordPL/strata-data) to get the formula for AF flag update for `decb %bl` instruction. 
 
`stoke debug circuit --strata_path "../strata-data/circuits" --code "decb %bl"`

```
%af    : (0xf₅ + 0x0₁ ∘ %rbx[3:0])[4:4] = 0x1₁
```
But for the assembly code:

```
movq  $0, %rbx
decb %bl
```
gdb sets the auxiliary flag after executing `decb`, but the above formula will not.
```
(0xf₅ + 0x0₁ ∘ %rbx[3:0])[4:4] = (0 1111 + 0 0000 ) [4:4] =/= 0x1
```
Also with `adcb $al, %bl`
The folrmula
```
%af    : (0x0₁ ∘ %rax[3:0] + 0x0₁ ∘ %rbx[3:0])[4:4] = 0x1₁
```
is not in sync with gdb results (eg: al == 0x7f bl = 0x00 and cf == 0x1) as it does not involve carry.

Please let me know your opinion.

**Comment by stefanheule** [comment]
For strata we decided not to model the `%af` flag, and so none of the formulas for `%af` are correct.  The fact that we even show it is a bug and should not be done.

There is no deep reason for the exclusion of `%af`: It just isn't a very commonly used flag, and the base formulas we had did not have `%af`, so we decided to omit it as well.
